# Generated by Django 4.0.9 on 2023-02-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dotprivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotprivate',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
