# Generated by Django 4.0.9 on 2023-02-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dotprivate_public'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DotPrivate',
            new_name='Dot',
        ),
    ]
